title: projecttri2
description: "August 2023 to June 2024"
owner_name: Aidan Lau
github_username: AidanLau10
github_repo: "projecttri2"
baseurl: "/projecttri2"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: github, user_url: "https://github.com/Tirth-Thakkar"}
    - { platform: github, user_url: "https://github.com/h4seeb-cmd"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
